### PR TITLE
Update Addon to Include  Palace and Mechagon

### PR DESCRIPTION
**Pull request by srhinos**
Tried to keep formatting consistent as well. Wanted to push what I did locally as I love this addon and wanted to keep the advanced filtering going

### CODE REVIEW

**Comment by 0xbs** [comment]
Thank you very much for your work and for the pull request!

**Comment by 0xbs** [comment]
New version 1.28 includes your changes and has just been released

**Comment by srhinos** [comment]
Awesome! If you need any help adding any additional functionality lmk. I'm not great with Lua but develop professionally so doubt it'd be much of an effort

**Comment by 0xbs** [comment]
If you don’t mind, you could test the current master on a live server. I don’t currently have a subscription and I am unsure if I should pay for a month just for some testing. The class-role keywords like `dps_priests>0` or `warrior_tanks>0` should still do their job and an error message should pop up if nonexistent keywords are used as in `opm or foo`.

Keywords page is also up to date.

**Comment by srhinos** [comment]
awesome, pulling and testing right now. I'll update if any issues

**Comment by srhinos** [comment]
Just tested it and everything was functioning properly except non-defined keywords throwing errors. It still throws errors if you insert a space. 

Example: 
`foo` or `foo and bar` just returns no matches
`foo bar` throws a Syntax Error

Hope this helps!

**Comment by 0xbs** [comment]
Thank you!

**Pull request merged**
